package proyectofinal;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class frmempleadosSuper extends javax.swing.JFrame {

    ResultSet rs = null;
    Empleado emp = new Empleado();
    int cantidad_de_registro = 0;
    int ultimo_registro = 0;
    boolean nuevo_empleado = false;//nuevo empleado
    boolean empleado_existente = false;//busqueda empleado
    boolean verificacion = false;//verificando para eliminar

    public frmempleadosSuper() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/icono/registrador.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btng1 = new javax.swing.ButtonGroup();
        Panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbestadoCivil = new javax.swing.JComboBox<>();
        rdbM = new javax.swing.JRadioButton();
        rdbF = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtidEmpleado = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        lblTelefono = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblDui = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cmbtipoEmpleado = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        ftxtfechanacimiento = new javax.swing.JFormattedTextField();
        ftxtdui = new javax.swing.JFormattedTextField();
        ftxtTelefono = new javax.swing.JFormattedTextField();
        lblGuardar = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnGuardarModif = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel1.setBackground(new java.awt.Color(255, 255, 255));
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/codigo-de-barras.png"))); // NOI18N
        jLabel1.setText("Id Empleado:");
        Panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 40));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tarjeta-de-identificacion.png"))); // NOI18N
        jLabel2.setText("Nombre/s:");
        Panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 130, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tarjeta-de-identificacion.png"))); // NOI18N
        jLabel3.setText("Apellido/s:");
        Panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 120, 20));

        cmbestadoCivil.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cmbestadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Soltero", "Casado", "Divorciado", "Viudo" }));
        Panel1.add(cmbestadoCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 110, 20));

        btng1.add(rdbM);
        rdbM.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rdbM.setText("Masculino");
        rdbM.setBorder(null);
        Panel1.add(rdbM, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        btng1.add(rdbF);
        rdbF.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        rdbF.setText("Femenino");
        rdbF.setBorder(null);
        Panel1.add(rdbF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/identificador.png"))); // NOI18N
        jLabel4.setText("Dui:");
        Panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estado-civil.png"))); // NOI18N
        jLabel6.setText("Estado Civil:");
        Panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/correo-electronico.png"))); // NOI18N
        jLabel7.setText("Correo Electrónico:");
        Panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sexo.png"))); // NOI18N
        jLabel8.setText("Sexo:");
        Panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/llamada.png"))); // NOI18N
        jLabel9.setText("Telefono :");
        Panel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 110, 40));

        txtCorreo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtCorreo.setBorder(null);
        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });
        Panel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 270, -1));

        txtidEmpleado.setEditable(false);
        txtidEmpleado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtidEmpleado.setBorder(null);
        Panel1.add(txtidEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 70, 20));

        txtnombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtnombre.setBorder(null);
        txtnombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtnombreFocusLost(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        Panel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 230, 20));

        txtapellido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtapellido.setBorder(null);
        txtapellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtapellidoFocusLost(evt);
            }
        });
        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidoKeyTyped(evt);
            }
        });
        Panel1.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 250, 20));
        Panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 450, 10));
        Panel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 450, -1));
        Panel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 450, 10));
        Panel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 450, 10));
        Panel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 450, 10));
        Panel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 450, 10));
        Panel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 450, 10));

        lblTelefono.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblTelefono.setForeground(new java.awt.Color(255, 51, 51));
        Panel1.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 440, 20));

        lblNombre.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 51, 51));
        Panel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 450, 20));

        lblApellido.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(255, 51, 51));
        Panel1.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 450, 20));

        lblFecha.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 51, 51));
        Panel1.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 450, 20));

        lblDui.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblDui.setForeground(new java.awt.Color(255, 51, 51));
        Panel1.add(lblDui, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 450, 20));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleado.png"))); // NOI18N
        jLabel18.setText("Tipo de Empleado:");
        Panel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        cmbtipoEmpleado.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cmbtipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Cajero", "Ordenanza", "Vendedor", "Almacen" }));
        Panel1.add(cmbtipoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 110, 20));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fecha-tope.png"))); // NOI18N
        jLabel20.setText("Fecha de Nacimiento:");
        Panel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 210, -1));

        ftxtfechanacimiento.setBorder(null);
        try {
            ftxtfechanacimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtfechanacimiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtfechanacimientoFocusLost(evt);
            }
        });
        ftxtfechanacimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxtfechanacimientoKeyTyped(evt);
            }
        });
        Panel1.add(ftxtfechanacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 90, 20));

        ftxtdui.setBorder(null);
        try {
            ftxtdui.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtdui.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        ftxtdui.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtduiFocusLost(evt);
            }
        });
        ftxtdui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxtduiKeyTyped(evt);
            }
        });
        Panel1.add(ftxtdui, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 110, 20));

        ftxtTelefono.setBorder(null);
        try {
            ftxtTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftxtTelefonoFocusLost(evt);
            }
        });
        ftxtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxtTelefonoKeyTyped(evt);
            }
        });
        Panel1.add(ftxtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 120, 20));

        lblGuardar.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblGuardar.setForeground(new java.awt.Color(255, 51, 51));
        Panel1.add(lblGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 440, 20));

        lblCorreo.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(255, 51, 51));
        Panel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 440, 20));

        getContentPane().add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 520, 600));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_btn/anadir.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 180, -1));

        btnbuscar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_btn/lupa.png"))); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 180, -1));

        btneliminar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_btn/cancelar.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 180, -1));

        btnModificar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_btn/editar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        btnSalir.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_btn/cerrar-sesion.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 180, -1));

        btnGuardar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_btn/disquete (1).png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 170, -1));

        btnGuardarModif.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnGuardarModif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_btn/guardar-datos.png"))); // NOI18N
        btnGuardarModif.setText("Guardar Modificacion");
        btnGuardarModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarModifActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardarModif, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 200, -1));

        btnCancelar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_btn/atras.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 540, 170, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 600));

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void Limpiarlbl() {
        lblGuardar.setText("");
        lblNombre.setText("");
        lblApellido.setText("");
        lblFecha.setText("");
        lblDui.setText("");
        lblTelefono.setText("");
        lblCorreo.setText("");
    }

    private void Limpiar() {
        txtnombre.setText("");
        txtapellido.setText("");
        ftxtfechanacimiento.setText("");
        ftxtdui.setText("");
        btng1.clearSelection();
        cmbestadoCivil.setSelectedIndex(0);
        cmbtipoEmpleado.setSelectedIndex(0);
        ftxtTelefono.setText("");
        txtCorreo.setText("");
    }

    private void Bloquear() {
        txtidEmpleado.setEnabled(false);
        txtnombre.setEnabled(false);
        txtapellido.setEnabled(false);
        ftxtfechanacimiento.setEnabled(false);
        rdbM.setEnabled(false);
        rdbF.setEnabled(false);
        cmbestadoCivil.setEnabled(false);
        cmbtipoEmpleado.setEnabled(false);
        ftxtdui.setEnabled(false);
        ftxtTelefono.setEnabled(false);
        txtCorreo.setEnabled(false);

    }

    private void Desbloquear() {
        txtidEmpleado.setEnabled(true);
        txtnombre.setEnabled(true);
        txtapellido.setEnabled(true);
        ftxtfechanacimiento.setEnabled(true);
        rdbM.setEnabled(true);
        rdbF.setEnabled(true);
        cmbestadoCivil.setEnabled(true);
        cmbtipoEmpleado.setEnabled(true);
        ftxtdui.setEnabled(true);
        ftxtTelefono.setEnabled(true);
        txtCorreo.setEnabled(true);

    }

    private void ftxtfechanacimientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtfechanacimientoFocusLost
        if (ftxtfechanacimiento.getText().equals("  /  /    ")) {
            lblFecha.setText("Ingrese una fecha porfavor");
        } else {
            Date fchactual = new Date();
            SimpleDateFormat formato = new SimpleDateFormat("yyyyMMdd");
            String cadenaFecha = formato.format(fchactual);
            String día = "" + cadenaFecha.charAt(6) + "" + cadenaFecha.charAt(7);
            String mes = "" + cadenaFecha.charAt(4) + "" + cadenaFecha.charAt(5);
            String año = "" + cadenaFecha.charAt(0) + "" + cadenaFecha.charAt(1) + "" + cadenaFecha.charAt(2) + "" + cadenaFecha.charAt(3);
            int d = Integer.parseInt(día);
            int m = Integer.parseInt(mes);
            int y = Integer.parseInt(año);
            String texto = this.ftxtfechanacimiento.getText();
            String dias = texto.charAt(0) + "" + texto.charAt(1);
            String meses = texto.charAt(3) + "" + texto.charAt(4);
            String años = texto.charAt(6) + "" + texto.charAt(7) + "" + texto.charAt(8) + "" + texto.charAt(9);
            int day = Integer.parseInt(dias);
            int month = Integer.parseInt(meses);
            int year = Integer.parseInt(años);
            if ((day <= 0) || (day > 31) || (month < 1) || (month > 12) || (year > y)) {
                lblFecha.setText("Fecha que ha ingresado invalida");
                this.ftxtfechanacimiento.setText("");
                this.ftxtfechanacimiento.requestFocus();
            } else if ((year < 1920)) {
                lblFecha.setText("El año que ha ingresado es incoherente");
                this.ftxtfechanacimiento.setText("");
                this.ftxtfechanacimiento.requestFocus();
            } else if ((year == y) && (day > d)) {
                if (d >= 10) {
                    lblFecha.setText("El día no puede ser mayor al día actual (" + d + ")");
                    this.ftxtfechanacimiento.setText("");
                    this.ftxtfechanacimiento.requestFocus();
                } else {
                    lblFecha.setText("El día no puede ser mayor al día actual (0" + d + ")");
                    this.ftxtfechanacimiento.setText("");
                    this.ftxtfechanacimiento.requestFocus();
                }
            } else if ((year == y) && (month > m)) {
                if (m >= 10) {
                    lblFecha.setText("El mes no puede ser mayor al mes actual (" + m + ")");
                    this.ftxtfechanacimiento.setText("");
                    this.ftxtfechanacimiento.requestFocus();
                } else {
                    lblFecha.setText("El mes no puede ser mayor al mes actual (0" + m + ")");
                    this.ftxtfechanacimiento.setText("");
                    this.ftxtfechanacimiento.requestFocus();
                }
            } else {
                lblFecha.setText("");
            }
        }
    }//GEN-LAST:event_ftxtfechanacimientoFocusLost

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        char validartext = evt.getKeyChar();
        if (!Character.isLetter(validartext) && validartext != KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyTyped
        char validartext = evt.getKeyChar();
        if (!Character.isLetter(validartext) && validartext != KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_txtapellidoKeyTyped

    private void txtapellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtapellidoFocusLost
        lblApellido.setText(ValidarTexto(txtapellido.getText()));
    }//GEN-LAST:event_txtapellidoFocusLost

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        rs = null;
        rs = emp.contarRegistros();
        try {
            while (rs.next()) {
                cantidad_de_registro = rs.getInt(1);
                if (cantidad_de_registro != 0) {
                    rs = null;
                    rs = emp.mayorRegistro();
                    while (rs.next()) {
                        ultimo_registro = rs.getInt(1) + 1;
                        if (ultimo_registro < 10) {
                            txtidEmpleado.setText("0000" + ultimo_registro);
                        } else if (ultimo_registro < 100) {
                            this.txtidEmpleado.setText("000" + ultimo_registro);
                        } else if (ultimo_registro < 1000) {
                            txtidEmpleado.setText("00" + ultimo_registro);
                        } else if (ultimo_registro < 10000) {
                            txtidEmpleado.setText("0" + ultimo_registro);
                        } else {
                            txtidEmpleado.setText("" + ultimo_registro);
                        }
                    }
                } else {
                    txtidEmpleado.setText("0000" + 1);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "ERROR: " + ex.getMessage());
        }
        txtnombre.requestFocus();
        Limpiar();
        Limpiarlbl();
        Desbloquear();
    }//GEN-LAST:event_btnNuevoActionPerformed
    /*VALIDACIONES DE BLOQUEAR ESPACIO EN FECHA DE NACIMIENTO*/
    private void ftxtfechanacimientoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtfechanacimientoKeyTyped
        char validarspace = evt.getKeyChar();
        if (validarspace == KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_ftxtfechanacimientoKeyTyped
    /*VALIDACIONES DE BLOQUEAR ESPACIO EN DUI*/
    private void ftxtduiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtduiKeyTyped
        char validarspace = evt.getKeyChar();
        if (validarspace == KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_ftxtduiKeyTyped
    /*VALIDACIONES DE BLOQUEAR ESPACIO EN TELEFONO*/
    private void ftxtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxtTelefonoKeyTyped
        char validarspace = evt.getKeyChar();
        if (validarspace == KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_ftxtTelefonoKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (nuevo_empleado = true) {
            if (lblNombre.getText().isEmpty() && lblApellido.getText().isEmpty() && lblFecha.getText().isEmpty() && (rdbM.isSelected() || rdbF.isSelected())
                    && lblDui.getText().isEmpty() && lblTelefono.getText().isEmpty() && lblCorreo.getText().isEmpty() && cmbestadoCivil.getSelectedIndex() != 0 && cmbtipoEmpleado.getSelectedIndex() != 0) {
                if (rdbM.isSelected() == true) {
                    emp.insertar(txtidEmpleado.getText(), txtnombre.getText(), txtapellido.getText(), ftxtfechanacimiento.getText(), "H", ftxtdui.getText(), String.valueOf(cmbestadoCivil.getSelectedItem()), String.valueOf(cmbtipoEmpleado.getSelectedItem()), ftxtTelefono.getText(), txtCorreo.getText());
                    JOptionPane.showMessageDialog(null, "Dato insertado con éxito", "AVISO DE NUEVO EMPLEADO", JOptionPane.INFORMATION_MESSAGE);
                    Bloquear();
                    Limpiar();
                    Limpiarlbl();
                    nuevo_empleado = false;
                } else {
                    emp.insertar(txtidEmpleado.getText(), txtnombre.getText(), txtapellido.getText(), ftxtfechanacimiento.getText(), "M", ftxtdui.getText(), String.valueOf(cmbestadoCivil.getSelectedItem()), String.valueOf(cmbtipoEmpleado.getSelectedItem()), ftxtTelefono.getText(), txtCorreo.getText());
                    JOptionPane.showMessageDialog(null, "Dato insertado con éxito", "AVISO DE NUEVO EMPLEADO", JOptionPane.INFORMATION_MESSAGE);
                    Bloquear();
                    Limpiar();
                    Limpiarlbl();
                    nuevo_empleado = false;
                }
            } else {
                lblGuardar.setText("Revise los campos anteriores porfavor");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void ftxtduiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtduiFocusLost
        if (ftxtdui.getText().equals("        - ")) {
            lblDui.setText("Error, no ha ingresado su Dui");
        } else {
            lblDui.setText("");
        }
    }//GEN-LAST:event_ftxtduiFocusLost

    private void ftxtTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftxtTelefonoFocusLost
        if (ftxtTelefono.getText().equals("    -    ")) {
            lblTelefono.setText("Error, no ha ingresado ningún número de celular");
        } else {
            lblTelefono.setText("");
        }
    }//GEN-LAST:event_ftxtTelefonoFocusLost
    /**
     * ****VALIDACION DE CORREO*****
     */
    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
        Pattern pattern = Pattern.compile("(\\\\W|^)[\\w.\\-]{0,25}@(hotmail|gmail|outlook|edu|yahoo)\\.com(\\W|$)");
        Matcher matcher = pattern.matcher(txtCorreo.getText());
        if (matcher.find()) {
            lblCorreo.setText("");
        } else {
            lblCorreo.setText("Error, correo ingresado no valido");
        }
    }//GEN-LAST:event_txtCorreoFocusLost

    private void txtnombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtnombreFocusLost
        lblNombre.setText(ValidarTexto(txtnombre.getText()));
    }//GEN-LAST:event_txtnombreFocusLost

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Limpiar();
        Limpiarlbl();
        Bloquear();
        txtidEmpleado.setText("");
        nuevo_empleado = false;
        verificacion = false;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Bloquear();
    }//GEN-LAST:event_formWindowOpened

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        String idEmpleado = JOptionPane.showInputDialog(null, "¿Cuál id empleado desea buscar?\n Ingrese su cógigo:", "BUSQUEDA", JOptionPane.INFORMATION_MESSAGE);
        rs = emp.buscar(idEmpleado);//Busqueda del id Empleado ingresado por el usuario.
        try {
            while (rs.next()) {
                txtidEmpleado.setText(rs.getString(1));
                txtnombre.setText(rs.getString(2));
                txtapellido.setText(rs.getString(3));
                ftxtfechanacimiento.setText(rs.getString(4));
                if (rs.getString(5).equals("H")) {
                    rdbM.setSelected(true);
                } else {
                    rdbF.setSelected(true);
                }
                ftxtdui.setText(rs.getString(6));
                cmbestadoCivil.setSelectedItem(rs.getString(7));
                cmbtipoEmpleado.setSelectedItem(rs.getString(8));
                ftxtTelefono.setText(rs.getString(9));
                txtCorreo.setText(rs.getString(10));
                verificacion = true;
                empleado_existente = true;
                nuevo_empleado = false;
            }
            if (empleado_existente == false) {
                JOptionPane.showMessageDialog(null, "Error, el Id que ingreso no existe", "RESPUESTA", JOptionPane.ERROR_MESSAGE);
                //this.txtCodigo.setText("");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage(), "AVISO DEL SISTEMA", 0);
        }
        empleado_existente = false;
        Limpiarlbl();
        Bloquear();
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if (verificacion == true) {
            String idEmpleado = txtidEmpleado.getText();
            if (JOptionPane.showConfirmDialog(rootPane, "¿Desea eliminar el registro búscado?") == 0) {
                emp.eliminar(idEmpleado);
                JOptionPane.showMessageDialog(null, "Registro eliminado exitosamente", "REGISTRO ELIMINADO", JOptionPane.OK_CANCEL_OPTION);
                Bloquear();
                Limpiar();
                txtidEmpleado.setText("");
                verificacion = false;
            }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String idEmpleado = JOptionPane.showInputDialog(null, "¿Cuál Id de empleado desea modificar?\n Ingrese su cógigo:", "BUSQUEDA", JOptionPane.INFORMATION_MESSAGE);
        rs = emp.buscar(idEmpleado);//Busqueda del id Empleado ingresado por el usuario.
        try {
            while (rs.next()) {
                txtidEmpleado.setText(rs.getString(1));
                txtnombre.setText(rs.getString(2));
                txtapellido.setText(rs.getString(3));
                ftxtfechanacimiento.setText(rs.getString(4));
                if (rs.getString(5).equals("H")) {
                    rdbM.setSelected(true);
                } else {
                    rdbF.setSelected(true);
                }
                ftxtdui.setText(rs.getString(6));
                cmbestadoCivil.setSelectedItem(rs.getString(7));
                cmbtipoEmpleado.setSelectedItem(rs.getString(8));
                ftxtTelefono.setText(rs.getString(9));
                txtCorreo.setText(rs.getString(10));
                verificacion = true;
                empleado_existente = true;
                nuevo_empleado = false;
            }
            if (empleado_existente == false) {
                JOptionPane.showMessageDialog(null, "Error, el Id que ingreso no existe", "RESPUESTA", JOptionPane.ERROR_MESSAGE);
                //this.txtCodigo.setText("");
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage(), "AVISO DEL SISTEMA", 0);
        }
        if (verificacion == true) {
            Desbloquear();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnGuardarModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarModifActionPerformed
        if (verificacion = true) {
            if (lblNombre.getText().isEmpty() && lblApellido.getText().isEmpty() && lblFecha.getText().isEmpty() && (rdbM.isSelected() || rdbF.isSelected())
                    && lblDui.getText().isEmpty() && lblTelefono.getText().isEmpty() && lblCorreo.getText().isEmpty() && cmbestadoCivil.getSelectedIndex() != 0 && cmbtipoEmpleado.getSelectedIndex() != 0) {
                if (rdbM.isSelected() == true) {
                    emp.modificar(txtidEmpleado.getText(), txtnombre.getText(), txtapellido.getText(), ftxtfechanacimiento.getText(), "H", ftxtdui.getText(), String.valueOf(cmbestadoCivil.getSelectedItem()), String.valueOf(cmbtipoEmpleado.getSelectedItem()), ftxtTelefono.getText(), txtCorreo.getText());
                    JOptionPane.showMessageDialog(null, "Modificacion realizada con éxito", "AVISO DE MODIFICACION", JOptionPane.INFORMATION_MESSAGE);
                    Limpiar();
                    Limpiarlbl();
                    Bloquear();
                    nuevo_empleado = false;
                    verificacion = false;
                } else {
                    emp.modificar(txtidEmpleado.getText(), txtnombre.getText(), txtapellido.getText(), ftxtfechanacimiento.getText(), "M", ftxtdui.getText(), String.valueOf(cmbestadoCivil.getSelectedItem()), String.valueOf(cmbtipoEmpleado.getSelectedItem()), ftxtTelefono.getText(), txtCorreo.getText());
                    JOptionPane.showMessageDialog(null, "Modificacion realizada con éxito", "AVISO DE MODIFICACION", JOptionPane.INFORMATION_MESSAGE);
                    Limpiar();
                    Limpiarlbl();
                    Bloquear();
                    nuevo_empleado = false;
                    verificacion = false;
                }
            } else {
                lblGuardar.setText("Revise los campos anteriores porfavor");
            }
        }
    }//GEN-LAST:event_btnGuardarModifActionPerformed

    /*VALIDACION DE NOMBRE Y APELLIDO */
    public String ValidarTexto(String texto) {
        try {
            if (!texto.isEmpty()) {
                return "";
            } else if (texto.isEmpty()) {
                return "Error, cuadro de texto vacio";
            }
        } catch (Exception e) {
            return "Error";
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmempleadosSuper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmempleadosSuper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmempleadosSuper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmempleadosSuper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmempleadosSuper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarModif;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.ButtonGroup btng1;
    private javax.swing.JComboBox<String> cmbestadoCivil;
    private javax.swing.JComboBox<String> cmbtipoEmpleado;
    private javax.swing.JFormattedTextField ftxtTelefono;
    private javax.swing.JFormattedTextField ftxtdui;
    private javax.swing.JFormattedTextField ftxtfechanacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDui;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblGuardar;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JRadioButton rdbF;
    private javax.swing.JRadioButton rdbM;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtidEmpleado;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
